<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Marketing_model extends CI_Model
{

    public $table = 'marketing';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id, nama, kode ,email, alamat, status_verify');
        $this->datatables->from('marketing');
        //add this line for join
        //$this->datatables->join('table2', 'marketing.field = table2.field');
        $this->datatables->add_column('action', 
        anchor(site_url('adminarea/marketing/delete/$1'),'<i class="fa fa-trash"></i>', 'class="btn btn-xs btn-danger" onclick="return confirmdelete(\'adminarea/marketing/delete/$1\')" data-toggle="tooltip" title="Delete"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('ktp', $q);
        $this->db->or_like('tlp', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('facebook', $q);
        $this->db->or_like('pengalaman', $q);
        $this->db->or_like('info', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('ktp', $q);
        $this->db->or_like('tlp', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('facebook', $q);
        $this->db->or_like('pengalaman', $q);
        $this->db->or_like('info', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }


    


}

/* End of file Marketing_model.php */
/* Location: ./application/models/Marketing_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-23 01:23:17 */
/* http://harviacode.com */