<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class DepositList extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$c_url = $this->router->fetch_class();
		$this->layout->auth();
		$this->layout->auth_privilege($c_url);
		$this->load->model('Deposit_model');
		$this->load->model('Users_pesan_model');
		$this->load->model('Log_model');
		$this->load->library('form_validation');
		$this->load->library('datatables');
	}

	public function index()
	{
		$data['title'] = 'Deposit';
		$data['subtitle'] = '';
		$data['crumb'] = [
			'Deposit' => '',
		];
		$data['code_js'] = 'deposit/codejsList';
		$data['page'] = 'deposit/deposit_list';
		$this->load->view('template/backend', $data);
	}

	public function json() {
		header('Content-Type: application/json');
		echo $this->Deposit_model->jsonList();
	}



	public function _rules()
	{
		$this->form_validation->set_rules('no_akun', 'no akun', 'trim|required');
		$this->form_validation->set_rules('nasabah_id', 'nasabah id', 'trim|required');
		$this->form_validation->set_rules('bank_id', 'bank id', 'trim|required');
		$this->form_validation->set_rules('total', 'total', 'trim|required|numeric');
		$this->form_validation->set_rules('acc_currency_id', 'acc currency id', 'trim|required');
		$this->form_validation->set_rules('bukti_transfer', 'bukti transfer', 'trim|required');
		$this->form_validation->set_rules('type_deposit', 'type deposit', 'trim|required');
		$this->form_validation->set_rules('status_deposit', 'status deposit', 'trim|required');
		$this->form_validation->set_rules('tanggal_deposit', 'tanggal deposit', 'trim|required');
		$this->form_validation->set_rules('id_operator', 'id operator', 'trim|required');

		$this->form_validation->set_rules('deposit_id', 'deposit_id', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
	}

	public function excel()
	{
		$this->load->helper('exportexcel');
		$namaFile = "deposit.xls";
		$judul = "deposit";
		$tablehead = 0;
		$tablebody = 1;
		$nourut = 1;
		//penulisan header
		header("Pragma: public");
		header("Expires: 0");
		header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
		header("Content-Type: application/force-download");
		header("Content-Type: application/octet-stream");
		header("Content-Type: application/download");
		header("Content-Disposition: attachment;filename=" . $namaFile . "");
		header("Content-Transfer-Encoding: binary ");

		xlsBOF();

		$kolomhead = 0;
		xlsWriteLabel($tablehead, $kolomhead++, "No");
		xlsWriteLabel($tablehead, $kolomhead++, "No Akun");
		xlsWriteLabel($tablehead, $kolomhead++, "Nama Nasabah");
		xlsWriteLabel($tablehead, $kolomhead++, "Email Nasabah");
		xlsWriteLabel($tablehead, $kolomhead++, "Total");
		xlsWriteLabel($tablehead, $kolomhead++, "Type Deposit");
		xlsWriteLabel($tablehead, $kolomhead++, "Status Deposit");
		xlsWriteLabel($tablehead, $kolomhead++, "Tanggal Deposit");

		foreach ($this->Deposit_model->get_by_all_join() as $data) {
			$kolombody = 0;

			//ubah xlsWriteLabel menjadi xlsWriteNumber untuk kolom numeric
			xlsWriteNumber($tablebody, $kolombody++, $nourut);
			xlsWriteNumber($tablebody, $kolombody++, $data->no_akun);
			xlsWriteLabel($tablebody, $kolombody++, $data->nama_lengkap);
			xlsWriteLabel($tablebody, $kolombody++, $data->email);
			xlsWriteNumber($tablebody, $kolombody++, number_format($data->total));
			xlsWriteLabel($tablebody, $kolombody++, $data->type_deposit);
			xlsWriteLabel($tablebody, $kolombody++, $data->status_deposit);
			xlsWriteLabel($tablebody, $kolombody++, $data->tanggal_deposit);

			$tablebody++;
			$nourut++;
		}

		xlsEOF();
		exit();
	}

	public function word()
	{
		header("Content-type: application/vnd.ms-word");
		header("Content-Disposition: attachment;Filename=deposit.doc");

		$data = array(
			'deposit_data' => $this->Deposit_model->get_by_all_join(),
			'start' => 0
		);

		$this->load->view('deposit/deposit_doc',$data);
	}

	public function printdoc(){
		$data = array(
			'deposit_data' => $this->Deposit_model->get_by_all_join(),
			'start' => 0
		);
		$this->load->view('deposit/deposit_print', $data);
	}

}

/* End of file Deposit.php */
/* Location: ./application/controllers/Deposit.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-12 00:06:04 */
/* http://harviacode.com */
