<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Withdraw_acc extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$c_url = $this->router->fetch_class();
		$this->layout->auth();
		$this->layout->auth_privilege($c_url);
		$this->load->model('Withdraw_model');
		$this->load->model('Users_pesan_model');
		$this->load->model('Log_model');
		$this->load->library('form_validation');
		$this->load->library('datatables');
	}

	public function index()
	{
		$data['title'] = 'Withdraw Transfer';
		$data['subtitle'] = '';
		$data['crumb'] = [
			'Withdraw' => '',
		];
		$data['code_js'] = 'withdraw/codeaccjs';
		$data['page'] = 'withdraw/withdraw_list';
		$this->load->view('template/backend', $data);
	}

	public function json() {
		header('Content-Type: application/json');
		echo $this->Withdraw_model->jsonaccWd();
	}


	public function update($id)
	{
		$row = $this->Withdraw_model->get_by_id_join($id);

		if($row->status_withdraw !== "Approve"){
			$this->session->set_flashdata('message', 'withdraw Belum Approve');
			redirect(site_url('adminarea/withdraw_acc'));
		}else{
			$data = array(
				'status_withdraw' => "Done",
			);
			$this->Withdraw_model->update($id, $data);
			$this->session->set_flashdata('message', 'Status withdraw Done');
			redirect(site_url('adminarea/withdraw_acc'));
		}
		
	}


	// public function updateoff($id){
    //     $is_active = "0";
	// 	$data = array(
	// 		'is_active' => $is_active,
	// 	);

	// 	if($this->Nasabah_model->update($id, $data)) // call the method from the model
	// 	{
	// 		$this->session->set_flashdata('message', 'Update Record gagal');
	// 		redirect(site_url('adminarea/nasabah'));
	// 	}
	// 	else{
	// 		$this->session->set_flashdata('message', 'Akun Di nonaktifkan');
	// 		redirect(site_url('adminarea/nasabah'));
	// 	}
    // }
}

/* End of file Withdraw.php */
/* Location: ./application/controllers/Withdraw.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-14 22:17:37 */
/* http://harviacode.com */
