<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Acc_currency_model extends CI_Model
{

    public $table = 'acc_currency';
    public $id = 'acc_currency_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    
    // datatables
    function json() {
        $this->datatables->select('acc_currency_id,nama_currency,deposit_rate,withdraw_rate,status_currency,tgl_update_cdeposit,tgl_update_cwithdraw');
        $this->datatables->from('acc_currency');
        //add this line for join
        //$this->datatables->join('table2', 'acc_currency.field = table2.field');
        $this->datatables->add_column('action', 
        anchor(site_url('adminarea/acc_currency/read/$1'),'<i class="fa fa-search"></i>', 'class="btn btn-xs btn-primary"  data-toggle="tooltip" title="Detail"')."  ".
        anchor(site_url('adminarea/acc_currency/update/$1'),'<i class="fa fa-edit"></i>', 'class="btn btn-xs btn-warning" data-toggle="tooltip" title="Edit"')."  ".
        anchor(site_url('adminarea/acc_currency/delete/$1'),'<i class="fa fa-trash"></i>', 'class="btn btn-xs btn-danger" onclick="return confirmdelete(\'/adminarea/acc_currency/delete/$1\')" data-toggle="tooltip" title="Delete"'), 'acc_currency_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('acc_currency_id', $q);
	$this->db->or_like('nama_currency', $q);
	$this->db->or_like('deposit_rate', $q);
	$this->db->or_like('withdraw_rate', $q);
	$this->db->or_like('status_currency', $q);
	$this->db->or_like('tgl_update_cdeposit', $q);
	$this->db->or_like('tgl_update_cwithdraw', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('acc_currency_id', $q);
	$this->db->or_like('nama_currency', $q);
	$this->db->or_like('deposit_rate', $q);
	$this->db->or_like('withdraw_rate', $q);
	$this->db->or_like('status_currency', $q);
	$this->db->or_like('tgl_update_cdeposit', $q);
	$this->db->or_like('tgl_update_cwithdraw', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }


}

/* End of file Acc_currency_model.php */
/* Location: ./application/models/Acc_currency_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-17 17:33:42 */
/* http://harviacode.com */