<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Log_model extends CI_Model
{

    public $table = 'nasabah_log';
    public $id = 'log_nasabah_id';
    public $table2 = 'log_user';
    public $id2 = 'log_users_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    function insert_admin($data)
    {
        $this->db->insert($this->table2, $data);
    }

    function get_by_nasabah_id($id)
    {
        $this->db->select('*');
        $this->db->from('nasabah_log');
        $this->db->where('nasabah_id', $id);
        // $this->db->like('tanggal', date('Y-m-d'), 'after');
        $this->db->limit(10);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get()->result();
    }

    function get_by_user_id($id)
    {
        $this->db->select('*');
        $this->db->from('log_user');
        $this->db->where('user_id', $id);
        $this->db->limit('10');
        $this->db->like('tanggal', date('Y-m-d'), 'after');
        $this->db->order_by($this->id2, $this->order);
        return $this->db->get()->result();
    }

    function get_count_unread_deposit()
    {
        return $this->db->select("*")
            ->from('log_user')
            ->where('read_status', 'N')
            ->where('type', 'Deposit')
            ->count_all_results();
    }

    function get_data_unread_deposit()
    {
        return $this->db->select("*")
            ->from('log_user')
            ->where('read_status', 'N')
            ->where('type', 'Deposit')
            ->join('nasabah', 'nasabah.nasabah_id=log_user.nasabah_id')
            ->get()->result();
    }

    function set_read_all_deposit()
    {
        $this->db->set('read_status', 'Y')
            ->where('read_status', 'N')
            ->where('type', 'Deposit')
            ->update('log_user');
    }

    function get_count_unread_nasabah()
    {
        return $this->db->select("*")
            ->from('log_user')
            ->where('read_status', 'N')
            ->where('type', 'Deposit')
            ->count_all_results();
    }

    function get_data_unread_nasabah()
    {
        return $this->db->select("*")
            ->from('log_user')
            ->where('read_status', 'N')
            ->where('type', 'Deposit')
            ->join('nasabah', 'nasabah.nasabah_id=log_user.nasabah_id')
            ->get()->result();
    }

    function set_read_all_nasabah()
    {
        $this->db->set('read_status', 'Y')
            ->where('read_status', 'N')
            ->where('type', 'Deposit')
            ->update('log_user');
    }
}

/* End of file Nasabah_model.php */
/* Location: ./application/models/Nasabah_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-03 03:39:28 */
/* http://harviacode.com */